version: '3'

services:
  Express-app:
    image: node:20.10.0
    container_name: API-EXPRESS
    working_dir: /Express
    ports:
      - "9002:9002"
    #pour run en dev avec nodemon
    command: sh -c "npm install && npm run dev"
    #pour run en classique avec node
    #command: sh -c "npm install && npm run start"
    depends_on:
      - SQL
      #- Storage-minio
    volumes:
      - ./BackEnd/Express:/Express

  Quasar-app:
    image: node:14
    container_name: API-QUASAR
    working_dir: /Quasar
    volumes:
      - ./FrontEnd/Quasar:/Quasar
    ports:
      - "9000:9000"
    command: sh -c "npm install && npm run dev"

  SQL:
    image: mysql:8.2.0
    container_name: APP-SQL
    environment:
      MYSQL_DATABASE: Ticketing_app
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./BackEnd/SQL_data:/var/lib/mysql

