version: '3'

services:
  Express-app:
    image: ${EXPRESS_IMG}
    container_name: API-EXPRESS
    working_dir: /Express
    ports:
      - "${EXPRESS_PORT}:9002"
    command: ${EXPRESS_CMD}
    depends_on:
      - Postgres
      #- Storage-minio
    volumes:
      - ${EXPRESS_VOLUME}

  Quasar-app:
    image: ${QUASAR_IMG}
    container_name: API-QUASAR
    working_dir: /Quasar
    volumes:
      - ${QUASAR_VOLUME}
    ports:
      - "${QUASAR_PORT}"
    command: sh -c "npm install && npm run build"

  Postgres:
    image: ${POSTGRES_IMG}
    container_name: API-POSTGRES
    environment:
      POSTGRES_DB: API-BDD
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ${POSTGRES_VOLUME}

  Minio-storage:
    image: minio/minio
    container_name: API-MINIO
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    ports:
      - "${MINIO_PORT}:9001"
    volumes:
      - ${MINIO_VOLUME}
    command: server --address :9001 /data

  Quasar-webserver:
    image: httpd:latest
    container_name: API-WEBSERVER
    volumes:
      - ${HTTPD_VOLUME}
    ports:
      - "${HTTPD_PORT}:80"
    restart: always
    depends_on:
      Quasar-app:
        condition: service_completed_successfully


